### ISSUE TITLE
Add auto-discovery of artifacts to import

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks-quarkus#16]
### Reason/Context

In the "Quarkus spirit" of Developer Joy, Convention over Configuration, and reducing plumbing & friction, it could be nice to implement auto-discovery of artifacts to import. 

So instead of having to declare these specific properties in `application.properties`:

```properties
quarkus.microcks.devservices.artifacts.primaries=target/classes/order-service-openapi.yaml,target/test-classes/third-parties/apipastries-openapi.yaml,target/test-classes/third-parties/hello-v1.proto
quarkus.microcks.devservices.artifacts.secondaries=target/test-classes/third-parties/apipastries-postman-collection.json,target/test-classes/third-parties/HelloService-postman-collection.json,target/test-classes/third-parties/HelloService-metadata.yml
```

we could rely on conventions so that artifacts located under `src/main/resources` and `src/test/resources` may be automatically discovered and imported into the MicrocksContainer during DevService startup.

### Description

This auto-discovery mechanism will only be applied if no `quarkus.microcks.devservices.artifacts.*` is defined. 

We propose to rely on naming conventions:
* All the files named `*-openapi.yml`, `*-openapi.yaml`, `*-openapi.json` will be imported as **primary** artifacts,
* All the files named `*-asyncapi.yml`, `*-asyncapi.yaml`, `*-asyncapi.json` will be imported as **primary** artifacts,
* All the files named `*.proto`, `*.graphql`, `*-soapui-project.xml` will also be imported as **primary** artifacts,
* All the files named `*postman-collection.json`, `*postman_collection.json` will be imported as **secondary** artifacts
* All the files named `*.har` will be imported as **secondary** artifacts,
* All the files named `*-metadata.yml`, `*-metadata.yaml` will also be imported as **secondary** artifacts,

**Comment by edeandrea** [comment]
Just for FYI - a `.proto` file would never be in `src/main/resources`. The grpc maven plugin looks in `src/main/proto` for those files. Maybe that location should be added to the search path for `.proto` files?

**Comment by lbroudoux** [comment]
Thanks for your comment @edeandrea. Will take in account for a next enhancement 😉
