### ISSUE TITLE
CORS issue?

### ISSUE THREAD

**Issue by edeandrea** [microcks/microcks-quarkus#22]
### Describe the bug

This came from https://github.com/quarkusio/quarkus-super-heroes/issues/687 - whats happening is I have a react app configured to talk to the Microcks dev service. Because its a browser request and my request is a POST, I'm getting a CORS issue because the React app is talking to a different port than where it was originally served from.

![image](https://github.com/microcks/microcks-quarkus/assets/363447/0afa91ef-8601-4627-b0aa-d6850e87d1b2)

You can see its doing the CORS pre-flight request

![image](https://github.com/microcks/microcks-quarkus/assets/363447/f2c6cfa0-dc51-4633-9e11-1da9d3f601b4)

which is then failing

![image](https://github.com/microcks/microcks-quarkus/assets/363447/d2a31a26-9e4c-44f2-8fab-5369540027d3)

How do I get around this?

### Microcks version or git rev

quay.io/microcks/microcks-uber:nightly

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

Quarkus dev service

**Comment by lbroudoux** [comment]
Hey @edeandrea!

Is this a regression? Did you have it working when using the `quay.io/microcks/microcks-uber:1.8.1` image?
CORS pref-flight are supposed to work but we've made some changes lately... I'll have to dive into them.

Thanks,

**Comment by edeandrea** [comment]
To be honest I've been using the nightly image for a while. I can try some previous images if you'd like.

I _think_ it was working at one point but to be honest I'm not sure I ever tried the POST request from the browser, so I can't be 100% sure it ever worked.

**Comment by lbroudoux** [comment]
Looks like we change the default value for `Access-Allow-Credentials` header. See https://github.com/Orange-OpenSource/microcks/commit/36dc55e1230867abec8fb0ec6ae67432e001f89c

Could you please try with putting the following configuration in `application.properties`:

```
quarkus.microcks.devservices.container-env.CORS_REST_ALLOW_CREDENTIALS=true
```

**Comment by edeandrea** [comment]
I'll give it a try tomorrow morning.

Thanks for the quick reply!

**Comment by lbroudoux** [comment]
We also have this issue/PR that is open and seems to be related to previous changes: https://github.com/microcks/microcks/pull/1061

**Comment by Apoorva64** [comment]
@lbroudoux i'm on it

**Comment by Apoorva64** [comment]
@lbroudoux It is due to the bump of the version of quarkus. The servlet Filters are not executed on OPTIONS request. I'm currently searching for another way to make it work

**Comment by lbroudoux** [comment]
Hey Eric. This should be solved with https://github.com/microcks/microcks/issues/1082
Can you try a fresher `nightly` container image?

**Comment by edeandrea** [comment]
Using the new `nightly` image the CORS preflight request goes through, but then the subsequent POST fails.

If I use something like Postman to make the POST (no CORS involved), I get what I would expect back.

![image](https://github.com/microcks/microcks-quarkus/assets/363447/084d1d35-f489-4b55-9e05-722152b95e27)

![image](https://github.com/microcks/microcks-quarkus/assets/363447/6eb2c981-8266-4d2d-b617-d3ba532818b6)

![image](https://github.com/microcks/microcks-quarkus/assets/363447/1938d315-ab8d-48ae-8dbc-94e717c554be)

**Comment by lbroudoux** [comment]
Weird... Can you see the second request actually hitting the microcks server with some logs?

**Comment by edeandrea** [comment]
Nothing in the microcks log when I try to do the POST request in the browser. I'm getting this in the browser:

```
localhost/:1  Access to XMLHttpRequest at 'http://localhost:58521/rest/Fights+API/1.0/api/fights' from origin 'http://localhost:8080' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.
```

**Comment by edeandrea** [comment]
If you need a good test bed for this the quarkus superheroes is easy to stand up.

1. Clone https://github.com/quarkusio/quarkus-super-heroes
2. `cd ui-super-heroes`
3. `./mvnw clean quarkus:dev`
4. Open browser to http://localhost:8080
5. Click the `Fight` button

**Comment by lbroudoux** [comment]
I will not be able to look at it in the coming hours as I'm speaking at a meetup. Will look at it probably tonight.

**Comment by edeandrea** [comment]
No worries.

Do you want me to try with

```
quarkus.microcks.devservices.container-env.CORS_REST_ALLOW_CREDENTIALS=true
```

?

**Comment by Apoorva64** [comment]
Can you make another screen with all the request headers? 

> Using the new `nightly` image the CORS preflight request goes through, but then the subsequent POST fails.
> 
> If I use something like Postman to make the POST (no CORS involved), I get what I would expect back.
> 
> ![image](https://private-user-images.githubusercontent.com/363447/304419546-084d1d35-f489-4b55-9e05-722152b95e27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MzQxNzUsIm5iZiI6MTcwNzgzMzg3NSwicGF0aCI6Ii8zNjM0NDcvMzA0NDE5NTQ2LTA4NGQxZDM1LWY0ODktNGI1NS05ZTA1LTcyMjE1MmI5NWUyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxNDE3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjk3ZjEzZDAwODIxMmJiZWRjMTQwN2JiNDRjYWFiNGYxYjVhOTBhOTVlNmU4MmFmMDJmYTdiMzM0M2YzNzgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SSACIy8_iBLf_5bdtV79cQzzMgyg38-DeSrBmsDHfQ0)
> 
> ![image](https://private-user-images.githubusercontent.com/363447/304419679-6eb2c981-8266-4d2d-b617-d3ba532818b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MzQxNzUsIm5iZiI6MTcwNzgzMzg3NSwicGF0aCI6Ii8zNjM0NDcvMzA0NDE5Njc5LTZlYjJjOTgxLTgyNjYtNGQyZC1iNjE3LWQzYmE1MzI4MThiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxNDE3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODU1NmM2M2Y5MWUyNTNiZDIwMmNiZWNjNDA0YTg0YzQyZmQ0OTkzOTkyMTQ3MWExYmYxYThlZDU2ZDM5MjE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0wrOMrZyNEI192ny2YwVGaHvWjf6x59P_5GteEqudrQ)
> 
> ![image](https://private-user-images.githubusercontent.com/363447/304419800-1938d315-ab8d-48ae-8dbc-94e717c554be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MzQxNzUsIm5iZiI6MTcwNzgzMzg3NSwicGF0aCI6Ii8zNjM0NDcvMzA0NDE5ODAwLTE5MzhkMzE1LWFiOGQtNDhhZS04ZGJjLTk0ZTcxN2M1NTRiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxNDE3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzBjOThiYjc5NmMxZDg5ZDAwZDk3NDIxYzdhYzZkMTNmMzFlM2E1NTIwNTUwOTk0NDg0MGM5ZjdiZGFlZDMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pf1SotCWnapuLkl0vuWYwgJ6k7l1kUFq5Dy5TLfv4LA)

**Comment by edeandrea** [comment]
Preflight request:
![image](https://github.com/microcks/microcks-quarkus/assets/363447/e3bf1380-699e-4612-83ef-f59f3f28cf7d)

POST request:
![image](https://github.com/microcks/microcks-quarkus/assets/363447/7ee6e993-8944-4568-b766-a60f6106a365)

**Comment by lbroudoux** [comment]
Hi @edeandrea,
Our latest changes should fix this issue. Can you have another test on a fresh `nightly` image and confirm it?

**Comment by edeandrea** [comment]
Hi @lbroudoux the latest `nightly` image seems to work! Thanks for the quick work!

**Comment by edeandrea** [comment]
I'd definitely be interested in helping or reviewing!

**Comment by lbroudoux** [comment]
Working on it this Friday! I'll let you as soon as I get something that can be used.
