### ISSUE TITLE
Live reloading of mock changes while in quarkus dev mode

### ISSUE THREAD

**Issue by rquinio1A** [microcks/microcks-quarkus#35]
### Reason/Context

While in quarkus:dev mode, changes to openapi-metadata.yaml file are not taken into account live, and you have to:
* restart quarkus:dev, which takes time as it has to restart the containers
* or use the Dev UI to delete and re-apply the metadata

### Description

It would be great if the extension would watch for changes in the mock files it has discovered, like other Quarkus extensions do.
The mocks should reload lazily:

* when a new request arrives in Quarkus
* or when accessing the Microcks DevUI, when verifying the mocks were correctly parsed.

### Implementation ideas

If it's fast, the simpler might be to drop and re-apply all the mocks even if the ones that have not changed, as un-merging primary + secondary artifacts could be tricky ?

**Comment by lbroudoux** [comment]
Thanks for opening the issue @rquinio1A! This is a good idea.

Would you have in mind another Quarkus DevServices that is doing such live-reloading stuff? It could help me to figure out how to implement this.

**Comment by rquinio1A** [comment]
Seems it has to do with `HotDeploymentWatchedFileBuildItem`, found this example: https://github.com/quarkiverse/quarkus-logging-logback/blob/934775dc2fc579108486bc4d40ca120a9d7887eb/impl/deployment/src/main/java/io/quarkiverse/logging/logback/deployment/LoggingLogbackProcessor.java#L80-L83

Also these general doc pointers might help:
* https://quarkus.io/guides/writing-extensions#integrating-with-development-mode 
* https://quarkus.io/guides/dev-ui#hot-reload

**Comment by lbroudoux** [comment]
We need first to apply #37 to have access to https://github.com/microcks/microcks-testcontainers-java/issues/45
